// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package Player

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type STATUS int32

const (
	STATUS_WAIT   STATUS = 0
	STATUS_READY  STATUS = 1
	STATUS_RUNING STATUS = 3
	STATUS_DONE   STATUS = 4
	STATUS_EXIT   STATUS = 5
)

var STATUS_name = map[int32]string{
	0: "WAIT",
	1: "READY",
	3: "RUNING",
	4: "DONE",
	5: "EXIT",
}

var STATUS_value = map[string]int32{
	"WAIT":   0,
	"READY":  1,
	"RUNING": 3,
	"DONE":   4,
	"EXIT":   5,
}

func (x STATUS) Enum() *STATUS {
	p := new(STATUS)
	*p = x
	return p
}

func (x STATUS) String() string {
	return proto.EnumName(STATUS_name, int32(x))
}

func (x *STATUS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STATUS_value, data, "STATUS")
	if err != nil {
		return err
	}
	*x = STATUS(value)
	return nil
}

func (STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

//protoc --go_out=. *.proto
//
type PlayerInfo struct {
	Nickname             *string  `protobuf:"bytes,1,req,name=nickname" json:"nickname,omitempty"`
	HeadImageUrl         *string  `protobuf:"bytes,2,req,name=headImageUrl" json:"headImageUrl,omitempty"`
	Address              *string  `protobuf:"bytes,3,req,name=address" json:"address,omitempty"`
	Gender               *uint64  `protobuf:"fixed64,4,req,name=gender" json:"gender,omitempty"`
	Privileges           *string  `protobuf:"bytes,5,opt,name=privileges" json:"privileges,omitempty"`
	Uid                  *uint64  `protobuf:"fixed64,6,req,name=uid" json:"uid,omitempty"`
	Coin                 *uint64  `protobuf:"fixed64,7,req,name=coin" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *PlayerInfo) GetHeadImageUrl() string {
	if m != nil && m.HeadImageUrl != nil {
		return *m.HeadImageUrl
	}
	return ""
}

func (m *PlayerInfo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *PlayerInfo) GetGender() uint64 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *PlayerInfo) GetPrivileges() string {
	if m != nil && m.Privileges != nil {
		return *m.Privileges
	}
	return ""
}

func (m *PlayerInfo) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *PlayerInfo) GetCoin() uint64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func init() {
	proto.RegisterEnum("STATUS", STATUS_name, STATUS_value)
	proto.RegisterType((*PlayerInfo)(nil), "PlayerInfo")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcb, 0x4a, 0xfc, 0x30,
	0x14, 0x87, 0xff, 0xbd, 0x4f, 0x0f, 0x7f, 0x21, 0x9c, 0x85, 0x04, 0x17, 0x52, 0x66, 0x55, 0x5c,
	0xe8, 0x13, 0xb8, 0xa8, 0x4c, 0x91, 0x6e, 0xaa, 0x64, 0x5a, 0xbc, 0xec, 0xc2, 0xe4, 0x58, 0x83,
	0x6d, 0x3a, 0x24, 0x2a, 0xf8, 0x7e, 0x3e, 0x98, 0x34, 0x5e, 0xd0, 0xdd, 0xf7, 0x7d, 0xbf, 0x64,
	0x73, 0xe0, 0x60, 0x22, 0xe7, 0xe4, 0x40, 0xa7, 0x7b, 0x3b, 0x3f, 0xcf, 0xeb, 0xf7, 0x00, 0xe0,
	0x7a, 0x94, 0x6f, 0x64, 0x1b, 0xf3, 0x30, 0xe3, 0x11, 0xac, 0x8c, 0xde, 0x3d, 0x19, 0x39, 0x11,
	0x0f, 0x8a, 0xb0, 0xcc, 0xc5, 0x8f, 0xe3, 0x1a, 0xfe, 0x3f, 0x92, 0x54, 0xcd, 0x24, 0x07, 0xea,
	0xed, 0xc8, 0x43, 0xbf, 0xff, 0x69, 0xc8, 0x21, 0x93, 0x4a, 0x59, 0x72, 0x8e, 0x47, 0x7e, 0xfe,
	0x56, 0x3c, 0x84, 0x74, 0x20, 0xa3, 0xc8, 0xf2, 0xb8, 0x08, 0xcb, 0x54, 0x7c, 0x19, 0x1e, 0x03,
	0xec, 0xad, 0x7e, 0xd5, 0x23, 0x0d, 0xe4, 0x78, 0x52, 0x04, 0x65, 0x2e, 0x7e, 0x15, 0x64, 0x10,
	0xbd, 0x68, 0xc5, 0x53, 0xff, 0x69, 0x41, 0x44, 0x88, 0x77, 0xb3, 0x36, 0x3c, 0xf3, 0xc9, 0xf3,
	0xc9, 0x39, 0xa4, 0xdb, 0xae, 0xea, 0xfa, 0x2d, 0xae, 0x20, 0xbe, 0xa9, 0x9a, 0x8e, 0xfd, 0xc3,
	0x1c, 0x12, 0x51, 0x57, 0x9b, 0x3b, 0x16, 0x20, 0x40, 0x2a, 0xfa, 0xb6, 0x69, 0x2f, 0x59, 0xb4,
	0x3c, 0xd8, 0x5c, 0xb5, 0x35, 0x8b, 0x17, 0xaa, 0x6f, 0x9b, 0x8e, 0x25, 0x17, 0xf9, 0x7d, 0x76,
	0xf6, 0x79, 0x85, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x76, 0xa4, 0x6c, 0x20, 0x01, 0x00,
	0x00,
}
