// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Student.proto

package Student

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//学生数据体
type Student struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Classes              string   `protobuf:"bytes,2,opt,name=classes,proto3" json:"classes,omitempty"`
	Grade                int32    `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4c3db915bb432d, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetClasses() string {
	if m != nil {
		return m.Classes
	}
	return ""
}

func (m *Student) GetGrade() int32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

//请求数据体定义
type StudentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentRequest) Reset()         { *m = StudentRequest{} }
func (m *StudentRequest) String() string { return proto.CompactTextString(m) }
func (*StudentRequest) ProtoMessage()    {}
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4c3db915bb432d, []int{1}
}

func (m *StudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentRequest.Unmarshal(m, b)
}
func (m *StudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentRequest.Marshal(b, m, deterministic)
}
func (m *StudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentRequest.Merge(m, src)
}
func (m *StudentRequest) XXX_Size() int {
	return xxx_messageInfo_StudentRequest.Size(m)
}
func (m *StudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentRequest proto.InternalMessageInfo

func (m *StudentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "Student")
	proto.RegisterType((*StudentRequest)(nil), "StudentRequest")
}

func init() { proto.RegisterFile("Student.proto", fileDescriptor_2f4c3db915bb432d) }

var fileDescriptor_2f4c3db915bb432d = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe5, 0x62, 0x87, 0x0a, 0x08,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x42, 0x12, 0x5c, 0xec, 0xc9, 0x39, 0x89, 0xc5, 0xc5, 0xa9, 0xc5, 0x12, 0x4c, 0x60, 0x61, 0x18,
	0x57, 0x48, 0x84, 0x8b, 0x35, 0xbd, 0x28, 0x31, 0x25, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x35,
	0x08, 0xc2, 0x51, 0x52, 0xe1, 0xe2, 0x83, 0x1a, 0x17, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x8c, 0xd5,
	0x54, 0x23, 0x4b, 0xb8, 0xaa, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x75, 0x2e, 0x2e,
	0xf7, 0xd4, 0x12, 0x98, 0x4b, 0xf8, 0xf5, 0x50, 0x0d, 0x91, 0xe2, 0x80, 0x09, 0x38, 0x71, 0x45,
	0x71, 0xe8, 0x43, 0xd9, 0x49, 0x6c, 0x60, 0x2f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94,
	0xcf, 0x49, 0x3b, 0xd3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StudentService service

type StudentServiceClient interface {
	//查询学生信息服务
	GetStudent(ctx context.Context, in *StudentRequest, opts ...client.CallOption) (*Student, error)
}

type studentServiceClient struct {
	c           client.Client
	serviceName string
}

func NewStudentServiceClient(serviceName string, c client.Client) StudentServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "studentservice"
	}
	return &studentServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *studentServiceClient) GetStudent(ctx context.Context, in *StudentRequest, opts ...client.CallOption) (*Student, error) {
	req := c.c.NewRequest(c.serviceName, "StudentService.GetStudent", in)
	out := new(Student)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StudentService service

type StudentServiceHandler interface {
	//查询学生信息服务
	GetStudent(context.Context, *StudentRequest, *Student) error
}

func RegisterStudentServiceHandler(s server.Server, hdlr StudentServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&StudentService{hdlr}, opts...))
}

type StudentService struct {
	StudentServiceHandler
}

func (h *StudentService) GetStudent(ctx context.Context, in *StudentRequest, out *Student) error {
	return h.StudentServiceHandler.GetStudent(ctx, in, out)
}
